### ISSUE TITLE
alias not found

### ISSUE THREAD

**Issue by tcurdt** [jandamm/zgenom#102]
This is what my `.zshrc` looks like:

```
source "${HOME}/.zgenom/zgenom.zsh"
zgenom autoupdate
if ! zgenom saved; then
  zgenom ohmyzsh
  zgenom ohmyzsh plugins/git
  zgenom ohmyzsh plugins/sudo
  zgenom ohmyzsh themes/daveverwer
  zgenom save
  zgenom compile "$HOME/.zshrc"
  zgenom compile $ZDOTDIR
fi

alias node14='export PATH="/opt/homebrew/opt/node@14/bin:$PATH"'
alias node16='export PATH="/opt/homebrew/opt/node@16/bin:$PATH"'
alias node17='export PATH="/opt/homebrew/opt/node@17/bin:$PATH"'
node14
```
With `zgenom` active I am getting

`/Users/tcurdt/.zshrc:35: command not found: node14`

while it works fine without.

Any idea what's going on?

**Comment by jandamm** [comment]
Hi @tcurdt,

this happens because of the `zgenom compile "$HOME/.zshrc"`.
The compilation uses the `-U` flag which suppresses the expansion of aliases when compiling.
So when sourcing the compiled file zsh is searching for a command `node14` in `$PATH` and does not find one.
When you then executed `node14` afterwards it'll work just fine.

Not expanding the aliases helped reduce some errors (#28, #31, #32) - mainly the compilation does not fail when the user has a conflicting alias in their config. 
In your case it introduces an error since you want the alias to work.

Probably controlling the `-U` flag would make sense. But I'm not sure whether it should default to on or off. (`zgenom`s automatic compiling wouldn't change)

Besides using this technique and often switch between versions will slow down your current shell. There's always a new directory prepended and when running a command a new directory has to checked for it (I'm not sure if zsh will filter out duplicates 🤷‍♂️).

**Comment by tcurdt** [comment]
Thanks for the explanation, @jandamm.

This is of course is only a very lightweight/crude approach to switching versions.
The slowdown isn't really an issue as the shell is usually only quite short lived.

I guess a quick workaround would be to just set PATH - not through a the alias. Not DRY but - well.

But how would I control the `-U` flag? Providing a `-h` didn't reveal anything.

**Comment by jandamm** [comment]
> But how would I control the -U flag? Providing a -h didn't reveal anything.

Currently you can't. I'll link a PR when I've implemented it.
It'll probably be the default **without* `-U` but `zgenom` will use the `-U` when called internally.

**Comment by jandamm** [comment]
Alright, I dug a bit deeper.

There are two things required for this to work:
1. The `-U` flag must not be provided
2. The aliases must be before the compile step (so before the zgenom block)*

\* This is because only aliases of the current shell are expanded when compiling. So `node14` has to be present in the current shell in order to be expanded into the compiled file.

Probably the easiest fix would be to just use a function instead:
```zsh
function node14() {
	export PATH="/opt/homebrew/opt/node@14/bin:$PATH"
}
function node16() {
	export PATH="/opt/homebrew/opt/node@16/bin:$PATH"
}
function node17() {
	export PATH="/opt/homebrew/opt/node@17/bin:$PATH"
}
node14
```
---
But I'll also provide a way to change the flags of zcompile. So `zgenom compile -Uz path` is valid an will use `zcompile -Uz` under the hood.

**Comment by jandamm** [comment]
Hey @tcurdt,

it should work when #106  is merged and your `.zshrc` is ordered like this:

```zsh
alias node14='export PATH="/opt/homebrew/opt/node@14/bin:$PATH"'
alias node16='export PATH="/opt/homebrew/opt/node@16/bin:$PATH"'
alias node17='export PATH="/opt/homebrew/opt/node@17/bin:$PATH"'
node14

source "${HOME}/.zgenom/zgenom.zsh"
zgenom autoupdate
if ! zgenom saved; then
  zgenom ohmyzsh
  zgenom ohmyzsh plugins/git
  zgenom ohmyzsh plugins/sudo
  zgenom ohmyzsh themes/daveverwer
  zgenom save
  zgenom compile "$HOME/.zshrc"
  zgenom compile $ZDOTDIR
fi
```

**Comment by tcurdt** [comment]
Sorry for the late reply (due to family time).
I also liked the `function` approach and are using that for now. But thanks for the fix!
