### ISSUE TITLE
explanation of files

### ISSUE THREAD

**Issue by tcurdt** [jandamm/zgenom#109]
Just a minor request for documentation.
I get that there is a compiled version of my `zshrc` - but why does it create 3 files?

```
.zcompdump
.zcompdump-Torsten’s MacBook Pro-5.8
.zcompdump.zwc
```

Or did I just skip this part while reading?
Would be great to have that documented somewhere.

**Comment by jandamm** [comment]
If you don't set `$ZGEN_CUSTOM_COMPDUMP` the naming of the compdump file is taken care by zsh itself.
Which is the `.zcompdump-Torsten’s MacBook Pro-5.8`.
I don't know where `.zcompdump` comes from.
The `.zcompdump.zwc` is created by zgenom since it searches for `$HOME/.zcompdump*` and compiles them.
The `.zcompdump-Torsten’s MacBook Pro-5.8.zwc` is probably not created since it contains `’`. See #100.

You could remove all three files, run `zgenom reset` and then check which files get created when you open a new shell.

Since the default name of Macs contains an invalid character (for `zcompile`) it might make sense that zgenom uses a different name instead to allow compiling.*

\* compiling the compdump is probably the biggest boost in startup speed.

**Comment by tcurdt** [comment]
Interesting. With setting `export ZGEN_CUSTOM_COMPDUMP=.zcompdump-foo` I now only have `.zshrc.zwc`
Thanks for the help.

**Comment by jandamm** [comment]
Yes, but the `.zcompdump-foo` and the according `.zwc` should be in `/` since you haven't used a full filepath.
`ZGEN_CUSTOM_COMPDUMP=$HOME/.zcompdump-foo` is probably better.

**Comment by tcurdt** [comment]
I don't have write access to `/`. So it didn't create anything there - but didn't complain either.

**Comment by tcurdt** [comment]
Hm. This doesn't create a `COMPDUMP` either:
```
export ZGEN_CUSTOM_COMPDUMP="${HOME}/.zcompdump-foo"
```
I'll keep an eye on that.

**Comment by jandamm** [comment]
Not sure if it creates a dump without `zgenom reset`.

**Comment by jandamm** [comment]
The zcompdump should be created no matter what.
The according zwc is only created after a `zgenom reset`.
