### ISSUE TITLE
Custom aliases not being loaded

### ISSUE THREAD

**Issue by bduff9** [jandamm/zgenom#112]
Hello!  I am not sure if this is the right place for this but wanted to start here as I really appreciated your help getting things working initially.  I am using p10k, zgenom, and ohmyzsh in a similar setup to the quickstart.  omz lets you add files to the custom directory that end in .zsh, and then auto loads those files (handy for things like aliases and functions).  I have 2 such files that were loading before switching to zgenom but are no longer loading.  I am not 100% sure if this is from zgenom or p10k, but wanted to start here because maybe you had some ideas or even ways I can troubleshoot/debug.  Thanks in advance!

**Comment by jandamm** [comment]
Sure thing.
Could you please check if `ls $ZSH/custom` lists the files you expect to be loaded?
If you're managing ohmyzsh with zgenom the ohmyzsh folder changed.

With `zgenom` (or probably any other plugin manager) it's not ideal to use the ohmyzsh way of loading custom files. Since the folder could be deleted with `zgenom clean`. It's also not so easy to track the `custom` folder with git.

I've switched to using this to load other scripts in my zshrc:
``` zsh
for file in $ZDOTDIR/after/*.zsh(N)
do
	source "$file"
done
```
(I have two folders: before and after, which are loaded before/after the zgenom script. [my dotfiles](https://github.com/jandamm/dotfiles))

**Comment by jandamm** [comment]
Alternatively you could set `$ZSH_CUSTOM` to the folder you expect to be sourced.

**Comment by bduff9** [comment]
@jandamm Awesome, thank you!  The info on the custom dir being different is what I needed.  I also appreciate you sharing your dotfiles as it gave me a better idea of how to set this up for what I need.  Everything seems to be working great now, so really appreciate your help and all your work on zgenom!
