### ISSUE TITLE
Option to silence output

### ISSUE THREAD

**Issue by bduff9** [jandamm/zgenom#123]
Hello!  Love the plugin, been using it for about 7 months.  One thing I don't see in the documentation (or my quick glance through the source) is a way to silence output.  The reason I ask is that I am using Powerlevel10k with instant prompt, which shows a warning every time that the .zshrc file has console output after p10k starts.  I get why outside of this use case having the console output is great or even needed, however, it would be nice if it could be turned off via an output to avoid seeing these warnings when I start a new console.  Specifically, this is what I am referencing as console output (the first line is from p10k):
```bash
-- console output produced during zsh initialization follows --

-- zgenom: Files in $ZGEN_RESET_ON_CHANGE changed; resetting `init.zsh`...
-- zgenom: Deleting `/Users/brianduffey/.zgenom/sources/init.zsh` ...
-- zgenom: Deleting `/Users/brianduffey/.config/zsh/.zcompdump_5.8*` ...
-- zgenom: Creating `/Users/brianduffey/.zgenom/sources/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
```

I can potentially also help with a PR if there is interest in this kind of option.  Let me know, thanks!

**Comment by jandamm** [comment]
Thank you.

First of all this should only appear if you changed your `.zshrc`. If it appears more often there is a bug in zgenom.

I use powerlevel10k as well. I decided to silence the warning emitted by p10k by setting `POWERLEVEL9K_INSTANT_PROMPT=quiet`.

Currently there is no way to silence the output of zgenom.
It also isn't trivial to implement as there are many calls which would have to be silenced.
The other question is whether updates/installs should also be silenced.

I'm planning to refactor the reset on change logic so that it is a command instead of a variable. The output of this command could then be silenced with redirection.

**Comment by jandamm** [comment]
Please reopen in case this error still exists.

**Comment by jandamm** [comment]
@bduff9 for `zgenom autoupdate` there is now the `--silent` option.

I plan to refactor the reset on change logic.
When the new api is ready I can have a look if I can add `--silent` there as well.
