### ISSUE TITLE
Please add details to the README with changes from stock zgen

### ISSUE THREAD

**Issue by unixorn** [jandamm/zgenom#13]
I think it's great that you're doing work on a zgen fork (and have added it to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list), but I'd like to see what updates you've made so I can consider replacing stock zgen with it in the [zsh-quickstart-kit](https://github.com/unixorn/zsh-quickstart-kit).

Thanks!

**Comment by jandamm** [comment]
Thanks for adding it 👍 

Here is a quick list I've done so far:
- compiling your sourced scripts 
- add `zgen compile` in case you want to recursively compile your dotfiles (manually)
- add `zgen bin` to add an executable to your `$PATH`
- lazy loading zgenom by sourcing `zgenom.zsh` instead of `zgen.zsh`

It also merges some pull requests and fixes bugs:
- compinit with custom flags wasn't working properly
- update to `ohmyzsh/ohmyzsh`
- allow cloning without submodules

This is all done with backwards compatibility in mind. So zgenom shouldn't require you to change anything of your existing zgen configuration. 

Things I might add in the future: (somewhat depends on the acceptance and my personal need)
- adding to `man`-pages
- conforming to the [zsh plugin standard](http://zdharma.org/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html)
- some sort of `zgen cleanup` or `zgen delete` to [remove unused plugins](https://github.com/tarjoilija/zgen/issues/103).

**Comment by jandamm** [comment]
Hey @unixorn,
I've added this list to the readme.
Do you want me to add some more information?

**Comment by unixorn** [comment]
I see the notes about `zgen bin` but not `zgen compile`, otherwise looks good

**Comment by jandamm** [comment]
Added `zgen compile`. I'll do a rewrite of the readme when I get around to it.
For now everything should be covered 👍

**Comment by unixorn** [comment]
Sweet, thanks.

**Comment by jandamm** [comment]
Please let me know how you decide with `zsh-quickstart-kit`.

Feel free to post here or create a new issue if there's something missing or you have another question 👍

**Comment by unixorn** [comment]
I did a talk on using the quickstart at work this week and didn't want to mess with it right before the talk. I'll give it a try this weekend, I'd rather be using zgenom since it's getting actively maintained.

Given that a lot of repos are moving to `main` instead of `master`, the repo checkout code probably needs a tweak to cope with that sooner rather than later.

**Comment by jandamm** [comment]
My idea was to get the default branch name from GitHub instead of assuming a master or main.

**Comment by unixorn** [comment]
Even better :-)

**Comment by unixorn** [comment]
Now that I'm thinking about it, maybe just clone the repo without specifying a branch unless the user specifies it in the `zgen load` command. Won't that end up with the repo's default branch?

Then the code wouldn't have to change if the user specifies a bitbucket or other git server besides GH.

**Comment by jandamm** [comment]
I've created an issue for that.

Exactly this was my idea. Then ideally on `zgen update` I check for those repositories if the default branch has changed and would start using the new branch. (After cloning you can ask a git remote for its head branch)

**Comment by unixorn** [comment]
I didn't know you could query a remote for its head branch, neat!
