### ISSUE TITLE
Add an unload command to unload the loaded plugin

### ISSUE THREAD

**Issue by neiromaster** [jandamm/zgenom#131]
In some other frameworks it is possible to unload some plugins, e.g. for testing or overlapping configurations, if they are written in different files. Is it possible to implement something similar here?

**Comment by jandamm** [comment]
Hey @neiromaster,

there's been a discussion about `zgenom unload ...` but it hasn't been implemented. https://github.com/jandamm/zgenom/issues/27#issuecomment-733921724

I'm still not sure it's worth implementing. It's nothing the plugin manager itself implements but it depends on the plugin to implement an `*_unload` function. I have no idea how wide spread this pattern is.
When I want to quickly want to switch plugins I enable [Watch for modifications](https://github.com/jandamm/zgenom#watch-files-for-modifications) and start a new shell.
I have a prototype which almost completely removes the performance penalty of Watch for modifications. So when this is ready it could even be kept enabled.

Since `zgenom unload` wouldn't need any internal api it could even be written as an [extension](https://github.com/jandamm/zgenom#extensions). There are three example extensions in case you want to give it a try.

**Comment by neiromaster** [comment]
Thanks for the reply! I just recently decided to get acquainted with Zi (https://wiki.zshell.dev/) and it has this feature. Thought it was implemented on the framework side. But if it's described in the standard and can be done as a module, it would be great if someone would do it. Maybe even me.

**Comment by jandamm** [comment]
Nice! In case you end up writing the extension I'll happy to include it into the README.

Have a look at the [eval](https://github.com/jandamm/zgenom-ext-eval) and [release](https://github.com/jandamm/zgenom-ext-release) extensions.

The unload logic would live in `functions/zgenom-unload`. You can use `functions/_zgenom-unload` to complete the cloned repos.
Finally in `init.zsh` you register the extension.

For completion you could complete `$ZGEN_DIR/*/*` which would be `username/repo` of all cloned repos.

**Comment by jandamm** [comment]
https://github.com/jandamm/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#4-unload-function

Here is the documentation for the unload requirements a plugin needs to implement.
