### ISSUE TITLE
errror - did not send all necessary objects

### ISSUE THREAD

**Issue by tcurdt** [jandamm/zgenom#142]
While "Breaking-Move" gives an idea, I am a little lost on what happened here.

```
Last zgenom autoupdate log:
--------
fatal: bad object refs/remotes/origin/Breaking-Move-zgen-compatibility-into-zgen.zsh.zwc
error: https://github.com/jandamm/zgenom.git did not send all necessary objects


-- zgenom: Deleting `/Users/tcurdt/.zgenom/sources/init.zsh` ...
-- zgenom: Deleting `/Users/tcurdt/.zcompdump-shodan2` ...

Recreating init.zsh

not saved
-- zgenom: Creating `/Users/tcurdt/.zgenom/sources/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
--------
```

Any pointers on how to fix this?

**Comment by V4G4X** [comment]
Facing the same issue recently.

**Comment by jandamm** [comment]
Hey @tcurdt, @V4G4X,

that issue isn't actually the Breaking change of #137.

The issue is that the branch of #137 ended in `.zsh`.
Git creates a file to keep track of that file `.git/refs/remotes/origin/Breaking-Move-zgen-compatibility-into-zgen.zsh`.
When `zgenom` compiles it sources the `.git` folder wasn't ignored. So `zgenom` created a `.git/refs/remotes/origin/Breaking-Move-zgen-compatibility-into-zgen.zsh.zwc`.
The next time Git checks for updates it cannot get an update on the branch `Breaking-Move-zgen-compatibility-into-zgen.zsh.zwc`.

I fixed this in #140.

In order to fix the current state you have to do the following:
```zsh
cd $ZGEN_SOURCE
rm -f ".git/refs/remotes/origin/Breaking-Move-zgen-compatibility-into-zgen.zsh.zwc"
git fetch --prune
git rebase origin/main
```
This will remove the faulty file and update `zgenom` so it won't happen again.

Please let me know if this fixes your issue 👍

**Comment by tcurdt** [comment]
Thank you so much, Jan.
That did the trick!

**Comment by V4G4X** [comment]
Thanks it fixes it for me too!

**Comment by jef** [comment]
Thank you for this and the hard work on zgenom 🙇
