### ISSUE TITLE
Occasional zsh processes pinning CPU

### ISSUE THREAD

**Issue by jzelinskie** [jandamm/zgenom#151]
I'm not sure what the root cause is, but after switching from zgen to zgenom, occasionally I get zsh processes not associated with any session that are pinned to 100% CPU.

I suspect it's a busy loop somewhere in an async process during an update, but that's just a guess.
I'm moreorless creating this issue to see if anyone else has experienced this before I start narrowing down the root cause.

PS: Thanks a ton for carrying the torch and maintaining the zgen legacy! 💞

**Comment by jandamm** [comment]
Thanks for reporting @jzelinskie. 

I haven't seen that issue but it could be the autoupdate. Other than that I don't think any detached zsh processes are used.

If you don't use autoupdate I don't think it's because of zgenom.
If you use autoupdate could it be that the update process is just slow?
You could try without autoupdate or add `--no-background` so it would run in the current zsh shell.
You could also remove `$ZGEN_DIR/.zgenom-*` to force an autoupdate for the next shell and then check a few minutes later if a rogue zsh exists.

autoupdate sources your zshrc in a non interactive shell. This might lead to an issue in some cases but seems fine for most users 🤷‍♂️

**Comment by jzelinskie** [comment]
When I start up a new shell, two zsh processes are created. I believe the second is from `zgenom prezto prompt theme 'sorin'` executing commands for its integration (e.g. git info).

I think migrating to zgenom maybe coincided with a change in version to prezto.

**Comment by jzelinskie** [comment]
Not resolved, but definitely upstream in prezto and not zgenom!

Seems very similar to: https://github.com/sorin-ionescu/prezto/issues/1701
