### ISSUE TITLE
slow, but possibly due to errors in compiling??

### ISSUE THREAD

**Issue by svenXY** [jandamm/zgenom#28]
Hi,
I just tried to switch to zgenom from zgen because I was trying to hunt down slow shell startups.

Slow here means >1.1s. Reading many other people's comments, I was under the impression to be able to get it down to about 0.5s which would be fine for me.

So I tried the migration and so on also did a zgenom reset and there I was presented with the following errors:

```sh
zgenom reset
-- zgenom: Deleting `/Users/myuserid/.zgenom/sources/init.zsh` ...

zsh                
-- zgenom: Creating `/Users/myuserid/.zgenom/sources/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump-mylaptop-5.8
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump-mylaptop-5.8.zwc
-zgen-compile:1: parse error near `)'
-zgen-compile:zcompile:3: can't read file: /Users/myuserid/.zcompdump-mylaptop-5.8.zwc
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump.zwc
-zgen-compile:1: parse error near `)'
-zgen-compile:zcompile:3: can't read file: /Users/myuserid/.zcompdump.zwc
-- zgenom: Creating `/Users/myuserid/.zgenom/sources/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump-mylaptop-5.8
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump-mylaptop.zwc
-zgen-compile:1: parse error near `)'
-zgen-compile:zcompile:3: can't read file: /Users/myuserid/.zcompdump-mylaptop-5.8.zwc
zgen-save:89: parse error: condition expected: /Users/myuserid/.zcompdump.zwc
-zgen-compile:1: parse error near `)'
-zgen-compile:zcompile:3: can't read file: /Users/myuserid/.zcompdump.zwc
```

I don't know enough about this compiling step, but could that mean that compiling actually fails and therefore my startup times remain high?

And if so - do you have an idea on how to hunt down the actual problem?

Here's my zprof for reference:

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         371,89   371,89   96,98%    172,83   172,83   45,07%  zgen-init
 2)    3         118,89    39,63   31,00%    118,89    39,63   31,00%  (anon)
 3)    1          56,48    56,48   14,73%     56,48    56,48   14,73%  handle_completion_insecurities
 4)    2          12,82     6,41    3,34%     12,82     6,41    3,34%  compinit
 5)    1          10,82    10,82    2,82%     10,82    10,82    2,82%  load-our-ssh-keys
 6)    1           6,28     6,28    1,64%      6,28     6,28    1,64%  _zsh_highlight_bind_widgets
 7)   20           1,72     0,09    0,45%      1,72     0,09    0,45%  compdef
 8)    1           1,08     1,08    0,28%      1,08     1,08    0,28%  colors
 9)    5           0,79     0,16    0,21%      0,79     0,16    0,21%  add-zsh-hook
10)    3           0,66     0,22    0,17%      0,66     0,22    0,17%  is-at-least
11)    3           0,57     0,19    0,15%      0,57     0,19    0,15%  bashcompinit
12)    4           0,61     0,15    0,16%      0,29     0,07    0,08%  complete
13)    1           0,07     0,07    0,02%      0,07     0,07    0,02%  group_lazy_load
14)    1           0,14     0,14    0,04%      0,05     0,05    0,01%  prompt_agnoster_setup
15)    1           0,05     0,05    0,01%      0,05     0,05    0,01%  detect-clipboard
16)    2           0,03     0,02    0,01%      0,03     0,02    0,01%  env_default
17)    1           0,03     0,03    0,01%      0,03     0,03    0,01%  zgen-saved
18)    1           0,05     0,05    0,01%      0,02     0,02    0,01%  zgenom
```

**Comment by svenXY** [comment]
zgenom ohmyzsh
zgenom ohmyzsh plugins/vi-mode
zgenom ohmyzsh plugins/pip
zgenom ohmyzsh plugins/sudo
zgenom ohmyzsh plugins/colored-man-pages
zgenom ohmyzsh plugins/git
zgenom ohmyzsh plugins/python
zgenom ohmyzsh plugins/rsync
zgenom ohmyzsh plugins/vagrant
zgenom ohmyzsh plugins/globalias
  zgenom ohmyzsh plugins/brew
  zgenom ohmyzsh plugins/osx
zgenom load zsh-users/zsh-history-substring-search
zgenom load unixorn/jpb.zshplugin
zgenom load unixorn/warhol.plugin.zsh
zgenom load unixorn/tumult.plugin.zsh
zgenom load djui/alias-tips
zgenom load unixorn/git-extra-commands
zgenom load skx/sysadmin-util
zgenom load svenXY/timewarrior
zgenom load agnoster/agnoster-zsh-theme agnoster.zsh-theme
zgenom load zsh-users/zsh-completions src
zgenom load srijanshetty/docker-zsh
zgenom load RobSis/zsh-completion-generator
zgenom load zsh-users/zsh-autosuggestions
zgenom save
 
is what I want to load

**Comment by jandamm** [comment]
Does this happen when you open subsequent shells or just directly after running `zgenom reset`?

**Comment by jandamm** [comment]
Hi @svenXY 

I found an issue that might have affected you. Could you please checkout the branch `Fix-compiling-HOME-.zcompdump` and try again?

**Comment by jandamm** [comment]
As for the *slowness*.
`zgen-init` is very fast by itself as it just `source $ZGEN_INIT`. (Plus checking if the file exists).

When this takes longer it is due to the plugins sourced in this script.

If you want to investigate this further you can do `vim $ZGEN_INIT`.
Then find the section `# ### General modules` and comment out some of the `source` statements and profile again.

**Comment by jandamm** [comment]
I just played a bit with your config:

On my machine commenting out any `source` statement results in `~10ms` of runtime of `zgen-init`.
Just running `zgenom ohmyzsh` adds about `110ms` to the load time.
Of course the config doesn't work without `zgenom ohmyzsh` but it adds a lot of startup penalty.
You can reduce the penalty to `90ms` by setting `DISABLE_AUTO_UPDATE=true` before you start `zgenom`.

The other plugins add about `10ms` of startup time each when sourced, which results in about `360ms`.
Some other plugins add even more startup time by adding hooks which run before the first prompt as well.
For example `_alias_tips__preexec` (`djui/alias-tips`) added about `55ms` to the startup time.

If you want your prompt mainly to feel snappy have a look at [powerlevel10k](https://github.com/romkatv/powerlevel10k) which is able to render the prompt before every plugin is fully loaded.

Unfortunately there isn't much `zgenom` can do if a plugin takes some time to load it will take this time.
The main reason why `zgen[om]` is considered fast is because it doesn't have to execute (much) code to source your plugins. Some other plugin manager calculate which/how to source plugins on every start of a new shell. This has some advantages since they can conditionally load plugins.

**Comment by svenXY** [comment]
thank you very much for your detailed support, that helped a lot. I was able to bring startup time down to 0.84 seconds which feels good enough for me now (especially compared to almost 2 secs before...).

I also understood a lot more about zsh startup and how to profile it.

In my .zshrc, there is also the following code:
```sh
# Make it easy to append your own customizations that override the above by
# loading all files from the ~/.zshrc.d directory
mkdir -p ~/.zshrc.d
if [ -n "$(/bin/ls ~/.zshrc.d)" ]; then
  for dotfile in ~/.zshrc.d/*.zsh
  do
    if [ -r "${dotfile}" ]; then
      # uncomment for  profiling script sourcing
      # echo $(gdate "+%S.%4N") sourcing $dotfile
      source $dotfile
    fi
  done
fi
```

where I source some files for my own aliases, functions etc. There was e.g. `pyenv init - `, which eats about 0.6s and can either be improved with `pyenv init - --no-rehash` or even better by lazy-loading it (erikced/zsh-pyenv-lazy-load).

Uncommenting the echo in the snippet helped me a lot to identify where most time was consumed.

Thanks again, closing!
Sven

**Comment by svenXY** [comment]
Ah, forgot something:

Your patch removed the problem with compinit, but there is another one that happens when using the zsh-syntax-highlighting:

```
- zgenom: Compiling files ...
-zgen-compile:33: defining function based on alias `ls'
-zgen-compile:33: parse error near `()'
-zgen-compile:zcompile:3: can't read file: /Users/Sven/.zgenom/sources/zsh-users/zsh-syntax-highlighting-___/highlighters/main/test-data/function.zsh
-zgen-compile:33: defining function based on alias `ls'
-zgen-compile:33: parse error near `()'
-zgen-compile:zcompile:3: can't read file: /Users/Sven/.zgenom/sources/zsh-users/zsh-syntax-highlighting-___/highlighters/main/test-data/function.zsh
-- zgenom: Creating `/Users/Sven/.zgenom/sources/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
-zgen-compile:33: defining function based on alias `ls'
-zgen-compile:33: parse error near `()'
-zgen-compile:zcompile:3: can't read file: /Users/Sven/.zgenom/sources/zsh-users/zsh-syntax-highlighting-___/highlighters/main/test-data/function.zsh
-zgen-compile:33: defining function based on alias `ls'
-zgen-compile:33: parse error near `()'
-zgen-compile:zcompile:3: can't read file: /Users/Sven/.zgenom/sources/zsh-users/zsh-syntax-highlighting-___/highlighters/main/test-data/function.zsh
```

Any idea? And why 3 times?

Thanks again

**Comment by jandamm** [comment]
It's generally not advisable to call executables in your `.zshrc` as it will slow execution down.
I use `rbenv` which is quite similar to `pynenv` and use it like this:
```zsh
if ! zgenom saved; then
        # ...
	rbenv init - > path/rbenv.zsh
fi
source path/rbenv.zsh
```
So whenever I run `zgenom reset` rbenv will reinit itself. Otherwise a "cached" version is used.

----
From what I've seen so far zsh cannot compile files which overwrite builtin commands.
The file you mention is a test file so it shouldn't be an issue. I could silence the errors produced while compiling but this would also silence correct errors (like the one you reported). 
I'll see if I can find a good solution.

----
I'm not really sure why it happens four times. Especially weird is that it happens before creating `init.zsh`.
Are you calling `zgenom compile` yourself?
Because the default steps are:
- Create init.zsh
- Initialize completions
- Compiling files
And you have the compiling step twice and then two errors each time.

**Comment by jandamm** [comment]
@svenXY I found the issue why the file generates two errors when compiling.
Still not sure why you see the compile step twice 🤔

**Comment by svenXY** [comment]
oops, found it myself: 

I had 

```sh
# if the init script doesn't exist
if ! zgenom saved; then

  # specify plugins here
  source $HOME/.zgenom-plugins

  # generate the init script from plugins above
  zgenom save
fi
# end zgenom
```

and in .zgenom-plugins, as last line, I had another `zgenom save`.

Sorry, that was my mistake. No more wondering necessary on your site ;-)

**Comment by jandamm** [comment]
Awesome 👏 
I'll add another PR and then both issues should be fixed.

Still not sure why compiling the one file doesn't work.
I'll see what I can do 👍

**Comment by jandamm** [comment]
I found out why the issue with `~/.zgenom/sources/zsh-users/zsh-syntax-highlighting-___/highlighters/main/test-data/function.zsh` occurs.

You (or one of your plugins) probably define an alias `ls` before the compiling does happen.
Since compiling runs on `zgenom save` it runs after each plugin is sourced.

I think I can fix this by using a sub-shell 👍
