### ISSUE TITLE
Add autoupdate functionality

### ISSUE THREAD

**Issue by unixorn** [jandamm/zgenom#56]
Moving this to a new issue.

I like the idea of having the autoupdate being part of core, defaulting to off. I also like the idea of moving things into a bindir and having the things in there not even get sourced unless `ZGENOM_LOAD_XYZ` is set to minimize startup impact.

I don't really know how autoload functions work all that well, that might be enough of a performance saver to go with that over not sourcing unused functionality.

**Comment by jandamm** [comment]
Conceptually they're like bins (one file is one function) and they're only retrieved when used.
But instead of calling them directly they have to be registered first. Which creates kind of a shim. Not sure about the penalty of running the `autoload` but this could also be delayed by only autoloading when the user is initializing full zgenom (`zgen.zsh`) or even at a later point in time or via a `ZGENOM_LOAD_XYZ`.

The issue with bins is that they cannot mutate the current shell (which `zgenom load` and others do).

**Comment by jandamm** [comment]
What do you think about integrating it as `zgenom autoupdate`?

The init file would then look like this:

``` zsh
source .../zgenom.zsh

zgenom autoupdate 

if ! zgenom saved; then
    zgenom load ...
fi
```

**Comment by unixorn** [comment]
Have it as `zgenom autoupdate`, and have that only source the code and do anything when `ZGENOM_AUTOUPDATE_DAYS` is set and non-zero?

**Comment by jandamm** [comment]
No, if you don't have anything set, I'd still assume 7 days.

Anyone who doesn't want to use autoupdate in their config shouldn't call it.

``` zsh
source .../zgenom.zsh

if ! zgenom saved; then
    zgenom load ...
fi
```

**Comment by unixorn** [comment]
Just a head's up - I'm on call this week, it doesn't look like I'm going to get to work on this till the weekend, or maybe Monday.
