### ISSUE TITLE
Compile All The Things!

### ISSUE THREAD

**Issue by Tuurlijk** [jandamm/zgenom#94]
Compiling files like .zshrc and .zcompdump gives quite a speed improvement

I have a function that compiles all the things

```zsh
# The following code helps us by optimizing the existing framework.
# This includes zcompile, zcompdump, etc.
compileAllTheThings () {
  setopt EXTENDED_GLOB
  local zsh_glob='^(.git*|LICENSE|README.md|*.zwc)(.)'

  # zcompile the completion cache; siginificant speedup.
  for file in ${ZDOTDIR:-${HOME}}/.zcomp${~zsh_glob}; do
    zcompare ${file}
  done

  # zcompile .zshrc
  zcompare ${ZDOTDIR:-${HOME}}/.zshrc

  # Zgenom
  zgenom_mods=${ZDOTDIR:-${HOME}}/.zgenom/
  zcompare ${zgenom_mods}init.zsh
  zcompare ${zgenom_mods}zgenom.zsh
  for dir ('/zsh-users/' '/zdharma/' '/robbyrussell/oh-my-zsh-master/plugins/shrink-path/'); do
    if [ -d "${zgenom_mods}${dir}" ]; then
      for file in ${zgenom_mods}${dir}**/*.zsh; do
        zcompare ${file}
      done
    fi
  done
}
```

**Comment by jandamm** [comment]
Hey @Tuurlijk,

I'm not really sure what you mean.
Currently zgenom will compile itself, all plugins you install and the compdump file whenever you run `zgenom save`.
[See here](https://github.com/jandamm/zgenom/blob/ecd6af391b8d26ed9d18c8962e330b504766ae2e/functions/zgenom-save#L113).

In my experience compiling the `.zshrc` doesn't bring much of a performance boost - but this may vary depending on the size of the file.
Also depending on your knowledge of zsh you may not know why there are `.zwc` appearing in your config. That's why I've decided not do automatically compile the `.zshrc` or the `$ZDOTDIR`.
But for those choosing to do so there is `zgenom compile` which accepts a file or folder and will compile any files which changed and are zsh files.
In the [Example](https://github.com/jandamm/zgenom#example-zshrc) there's also the code given to compile your zsh files.

As stated above I do not feel comfortable to automatically compile files of the user without their consent. (Giving consent is in this case copying the lines from the example)

**Comment by Tuurlijk** [comment]
Ok, cool. Had not seen that genom can also compile zcompdump. That was the biggest speedup for me.

**Comment by jandamm** [comment]
It will compile `$ZGEN_CUSTOM_COMPDUMP` or if this is not used it compiles `$HOME/.zcompdump*`.
Maybe it would make sense to strengthen this glob by preferring `$ZDOTDIR` and just checking for `.zcomp*`.

What do you think?

**Comment by Tuurlijk** [comment]
Looks fine as it is. I don't seem to have a `$ZDOTDIR` in my env.
